---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-argo 
  namespace: openshift-gitops
spec:
  destination:
    namespace: sample-app
    server: https://kubernetes.default.svc
  project: default
  # change Project to 'group' Apps and apply specific settings
  # according to sourceRepos, destination-Namespaces and -Servers etc.
  #project: appproject-testing
  source:
    repoURL: https://github.com/k8strainer/sample-app-opns.git
    targetRevision: main
    path: k8s
  syncPolicy:
    automated:
      # prune resources in live cluster if not available any more in Git
      prune: true
      # By default, changes that are made to the live cluster will not trigger automated sync. 
      # To enable automatic sync when the live cluster's state deviates from the state defined in Git, run: 
      selfHeal: true
    # sync retry  
    retry:
      limit: 5
  
  ignoreDifferences:
  # needed, as otherwise route-weighting of argo.-rollout-route-plugin will be overriden 
  # by argoCD Sync from git
  - group: route.openshift.io
    kind: Route
    name: sample-app-route
    namespace: sample-app
    # optional: einzelne Felder, die ignoriert werden sollen
    jsonPointers:
    - /spec/to/weight
    - /spec/alternateBackends
